site_name: Voice Transcriber Documentation
site_description: Lightweight desktop voice-to-text transcription with OpenAI Whisper and system tray integration
site_url: https://nouuu.github.io/voice-transcriber
repo_url: https://github.com/Nouuu/voice-transcriber
repo_name: nouuu/voice-transcriber
edit_uri: edit/main/documentation/
docs_dir: documentation

theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Lien d'ancrage vers cette section
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nouuu
      repo: voice-transcriber
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - First Run: getting-started/first-run.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Language Support: user-guide/language-support.md
      - Transcription Backends: user-guide/transcription-backends.md
      - Troubleshooting: user-guide/troubleshooting.md
  - Development:
      - Architecture: development/architecture.md
      - Development Guide: development/development-guide.md
      - Testing: development/testing.md
      - API Reference: development/api-reference.md
  - Advanced:
      - Speaches Integration: advanced/speaches-integration.md
      - Whisper Models: advanced/whisper-models.md
      - Local Inference: advanced/local-inference.md
  - Contributing: contributing.md
  - Migration Guide: MIGRATION_GUIDE.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nouuu/voice-transcriber
      name: GitHub Repository
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/voice-transcriber
      name: NPM Package
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/Nouuu/voice-transcriber/issues/new?title=[Docs]&body=URL: {url}" target="_blank" rel="noopener">opening an issue</a>.

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Nouuu - MIT License
