name: Build

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [1.2.x, latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix.bun-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y alsa-utils

    - name: Install dependencies
      run: make install

    - name: Check system dependencies
      run: make check-deps

    - name: Build application
      run: make build