name: Lint

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'
  pull_request:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
      - 'assets/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: make install

    - name: Run Biome checks
      run: make lint

    - name: Check code formatting
      run: make format-check